spring:
  application:
    name: g33-spring-boot-active-use
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: b1t
    password: 15696psql
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jjwt:
  token:
    key:
      secret: O4xoGCVmFqHnkkbcOkqnD/yB2V/W8dpQpFXq981jDOt4dnyB0Ya+v1DpYNYh8N+UXSMfPCC9wCglXyjAgEKsRQ==
    time:
      expiration: 1200000
